### ISSUE TITLE
Return notes when retrieving volume details using cli

### ISSUE THREAD

**Issue by akashrajkn** [softlayer/softlayer-cli#1]
Original issue link: https://github.com/IBM-Cloud/ibm-cloud-cli-sdk/issues/302

### Issue description:
We can use `ibmcloud sl file volume-detail <id>` to get volume details. At the moment, it is missing notes field. 
Relevant commands: `ibmcloud sl file volume-detail`, `ibmcloud sl block volume-detail`

**Workaround for now**
```
ibmcloud sl call-api SoftLayer_Network_Storage getObject --init <id>
```

**Comment by allmightyspiff** [comment]
This is being added in https://github.ibm.com/SoftLayer/softlayer-cli/pull/215 and should hopefully be in the next release of the ibmcloud cli
