### ISSUE TITLE
Submit notes parameter while ordering a block/file volume via cli

### ISSUE THREAD

**Issue by akashrajkn** [softlayer/softlayer-cli#2]
At the moment, we cannot submit the notes parameter while creating a block/file volume. It would be nice to have edit `notes` field with the cli. (Since username is autogenerated, I use `notes` to name my volumes)

Relevant commands: 
```
ibmcloud sl file volume-order [OPTIONS]
ibmcloud sl block volume-order [OPTIONS]
```
Request: Add `--notes` to OPTIONS

**Comment by akashrajkn** [comment]
> `ibmcloud sl block|file volume-set-note`

This sounds awesome! In case it takes too much time (a few weeks) to develop this, let me know and I can give it a go and submit a PR.

Thank you so much for such a fast response :)

**Comment by allmightyspiff** [comment]
I was planning on taking a look at this Monday or Tuesday, and should be done within a week.
However if you want to add the feature yourself you are more than welcome to submit a pull request to this repo. Just let me know so were not both working on it.

**Comment by allmightyspiff** [comment]
This is fixed in https://github.ibm.com/SoftLayer/softlayer-cli/pull/217 and will be in the next version of the `softlayer-cli` project.
