### ISSUE TITLE
Filter volumes based on the notes via cli

### ISSUE THREAD

**Issue by akashrajkn** [softlayer/softlayer-cli#3]
At the moment, for getting a list of volumes, we can give username, datacenter, storage-type as parameters for the filter. It is quite handy to filter based on the user notes. Will it be supported in the future?

**Relevant commands**:
```
ibmcloud sl file volume-list [OPTIONS]
ibmcloud sl block volume-list [OPTIONS]
```
Request: Add `--notes` to OPTIONS

**Workaround for now**:
Note, this is possible using the `call-api`:
```
ibmcloud sl call-api SoftLayer_Account getNetworkStorage --filter '{"networkStorage":{"notes":{"operation":"a-fancy-volume"}}}'
```

**Comment by allmightyspiff** [comment]
This is added in https://github.ibm.com/SoftLayer/softlayer-cli/pull/221 and will be in the next release
